--==============================================================
-- PHASE 4A - USER_MODE_STATE (DISCIPLINE_RULE_ENGINE)
-- Persists STANDARD | MINIMUM so Scheduler does not rely on
-- one-shot pending mode changes alone.
-- Additive / idempotent. Safe to re-run.
--==============================================================
USE [DISCIPLINE_RULE_ENGINE]
GO

IF OBJECT_ID('dbo.USER_MODE_STATE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.USER_MODE_STATE (
        USERID INT NOT NULL,
        CURRENTMODE NVARCHAR(20) NOT NULL
            CONSTRAINT DF_UMS_CURRENTMODE DEFAULT (N'STANDARD'),
        CONSECUTIVEFAILURES INT NOT NULL
            CONSTRAINT DF_UMS_CONSECUTIVEFAILURES DEFAULT (0),
        CURRENTSTREAK INT NOT NULL
            CONSTRAINT DF_UMS_CURRENTSTREAK DEFAULT (0),
        MODEEFFECTIVEDATE DATE NULL,
        UPDATEDAT DATETIME2(7) NOT NULL
            CONSTRAINT DF_UMS_UPDATEDAT DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_USER_MODE_STATE PRIMARY KEY CLUSTERED (USERID),
        CONSTRAINT CHK_UMS_CURRENTMODE CHECK (CURRENTMODE IN (N'STANDARD', N'MINIMUM'))
    );
END
GO

-- Backfill from USERSTREAK + latest DAYEVALUATIONAUDIT.EVALUATIONMODE
MERGE dbo.USER_MODE_STATE AS T
USING (
    SELECT
        US.USERID,
        ISNULL(Latest.EVALUATIONMODE, N'STANDARD') AS CURRENTMODE,
        ISNULL(US.CONSECUTIVEFAILURES, 0) AS CONSECUTIVEFAILURES,
        ISNULL(US.CURRENTSTREAK, 0) AS CURRENTSTREAK,
        CAST(NULL AS DATE) AS MODEEFFECTIVEDATE
    FROM dbo.USERSTREAK US
    OUTER APPLY (
        SELECT TOP (1) DEA.EVALUATIONMODE
        FROM dbo.DAYEVALUATIONAUDIT DEA
        WHERE DEA.USERID = US.USERID
        ORDER BY DEA.DAYDATE DESC, DEA.EVALUATEDAT DESC
    ) Latest
) AS S
ON T.USERID = S.USERID
WHEN NOT MATCHED BY TARGET THEN
    INSERT (USERID, CURRENTMODE, CONSECUTIVEFAILURES, CURRENTSTREAK, MODEEFFECTIVEDATE, UPDATEDAT)
    VALUES (
        S.USERID,
        S.CURRENTMODE,
        S.CONSECUTIVEFAILURES,
        S.CURRENTSTREAK,
        S.MODEEFFECTIVEDATE,
        SYSUTCDATETIME()
    );
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_UPSERT_USER_MODE_STATE]
(
    @USERID INT,
    @CURRENTMODE NVARCHAR(20),
    @CONSECUTIVEFAILURES INT,
    @CURRENTSTREAK INT,
    @MODEEFFECTIVEDATE DATE = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    IF @USERID IS NULL OR @USERID <= 0
    BEGIN
        SELECT 1 AS ErrorCode, N'INVALID_USER' AS ErrorType, N'USERID is required' AS ErrorMessage;
        RETURN;
    END

    IF @CURRENTMODE IS NULL OR @CURRENTMODE NOT IN (N'STANDARD', N'MINIMUM')
    BEGIN
        SELECT 2 AS ErrorCode, N'INVALID_MODE' AS ErrorType,
               N'CURRENTMODE must be STANDARD or MINIMUM' AS ErrorMessage;
        RETURN;
    END

    DECLARE @Now DATETIME2(7) = SYSUTCDATETIME();
    DECLARE @Failures INT = ISNULL(@CONSECUTIVEFAILURES, 0);
    DECLARE @Streak INT = ISNULL(@CURRENTSTREAK, 0);

    MERGE dbo.USER_MODE_STATE AS T
    USING (SELECT @USERID AS USERID) AS S
    ON T.USERID = S.USERID
    WHEN MATCHED THEN
        UPDATE SET
            CURRENTMODE = @CURRENTMODE,
            CONSECUTIVEFAILURES = @Failures,
            CURRENTSTREAK = @Streak,
            MODEEFFECTIVEDATE = @MODEEFFECTIVEDATE,
            UPDATEDAT = @Now
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (USERID, CURRENTMODE, CONSECUTIVEFAILURES, CURRENTSTREAK, MODEEFFECTIVEDATE, UPDATEDAT)
        VALUES (@USERID, @CURRENTMODE, @Failures, @Streak, @MODEEFFECTIVEDATE, @Now);

    SELECT
        0 AS ErrorCode,
        N'SUCCESS' AS Status,
        USERID,
        CURRENTMODE,
        CONSECUTIVEFAILURES,
        CURRENTSTREAK,
        MODEEFFECTIVEDATE,
        UPDATEDAT
    FROM dbo.USER_MODE_STATE
    WHERE USERID = @USERID;
END
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_GET_USER_MODE_STATE]
(
    @USERID INT
)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM dbo.USER_MODE_STATE WHERE USERID = @USERID)
    BEGIN
        SELECT
            USERID,
            CURRENTMODE,
            CONSECUTIVEFAILURES,
            CURRENTSTREAK,
            MODEEFFECTIVEDATE,
            UPDATEDAT
        FROM dbo.USER_MODE_STATE
        WHERE USERID = @USERID;
        RETURN;
    END

    -- Defaults when no row yet (STANDARD)
    DECLARE @Failures INT = 0;
    DECLARE @Streak INT = 0;

    SELECT
        @Failures = ISNULL(CONSECUTIVEFAILURES, 0),
        @Streak = ISNULL(CURRENTSTREAK, 0)
    FROM dbo.USERSTREAK
    WHERE USERID = @USERID;

    SELECT
        @USERID AS USERID,
        N'STANDARD' AS CURRENTMODE,
        @Failures AS CONSECUTIVEFAILURES,
        @Streak AS CURRENTSTREAK,
        CAST(NULL AS DATE) AS MODEEFFECTIVEDATE,
        CAST(NULL AS DATETIME2(7)) AS UPDATEDAT;
END
GO
